runtime: python39
entrypoint: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  API_KEY: ""  # Set this in GCP Console
  GOOGLE_PROJECT_NUMBER: ""  # Set this in GCP Console
  GOOGLE_LOCATION: "global"
  GOOGLE_CATALOG: "default_catalog"
  GOOGLE_SERVING_CONFIG: "default_config"

handlers:
- url: /.*
  script: auto