runtime: python39
entrypoint: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  API_KEY: "2fed9999056fab6dac5654238f0cae1c"
  GOOGLE_PROJECT_NUMBER: "178362262166"
  GOOGLE_LOCATION: "us-central1"
  GOOGLE_CATALOG: "default_catalog"
  GOOGLE_SERVING_CONFIG: "D:/Projects/AI/retail-recommender/service-account-key.json"
  ENABLE_EXTERNAL_SERVICES: "False"

handlers:
- url: /.*
  script: auto
