# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommendation_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'recommendation_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1crecommendation_service.proto\x12\x0erecommendation\"3\n\x0eProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"`\n\x12UserProductRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\x12\x16\n\x0e\x63ontent_weight\x18\x04 \x01(\x02\"\x86\x01\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\t\x12\r\n\x05score\x18\x06 \x01(\x02\x12\x1b\n\x13recommendation_type\x18\x07 \x01(\t\"\x8d\x01\n\x17RecommendationsResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x30\n\x0frecommendations\x18\x02 \x03(\x0b\x32\x17.recommendation.Product\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\t\"K\n\x10UserEventRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x12\n\nproduct_id\x18\x03 \x01(\t\"@\n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2\xa9\x03\n\x15RecommendationService\x12i\n\x1eGetContentBasedRecommendations\x12\x1e.recommendation.ProductRequest\x1a\'.recommendation.RecommendationsResponse\x12g\n\x18GetRetailRecommendations\x12\".recommendation.UserProductRequest\x1a\'.recommendation.RecommendationsResponse\x12g\n\x18GetHybridRecommendations\x12\".recommendation.UserProductRequest\x1a\'.recommendation.RecommendationsResponse\x12S\n\x0fRecordUserEvent\x12 .recommendation.UserEventRequest\x1a\x1e.recommendation.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendation_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTREQUEST']._serialized_start=48
  _globals['_PRODUCTREQUEST']._serialized_end=99
  _globals['_USERPRODUCTREQUEST']._serialized_start=101
  _globals['_USERPRODUCTREQUEST']._serialized_end=197
  _globals['_PRODUCT']._serialized_start=200
  _globals['_PRODUCT']._serialized_end=334
  _globals['_RECOMMENDATIONSRESPONSE']._serialized_start=337
  _globals['_RECOMMENDATIONSRESPONSE']._serialized_end=478
  _globals['_USEREVENTREQUEST']._serialized_start=480
  _globals['_USEREVENTREQUEST']._serialized_end=555
  _globals['_STATUSRESPONSE']._serialized_start=557
  _globals['_STATUSRESPONSE']._serialized_end=621
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=624
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=1049
# @@protoc_insertion_point(module_scope)
