runtime: python39
entrypoint: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  API_KEY: "2fed9999056fab6dac5654238f0cae1c"  # Set this in GCP Console
  GOOGLE_PROJECT_NUMBER: "178362262166"  # Set this in GCP Console
  GOOGLE_LOCATION: global
  GOOGLE_CATALOG: "default_catalog"
  GOOGLE_SERVING_CONFIG: "default_recommendation_config"
  # Nuevas variables para importación GCS
  GCS_BUCKET_NAME: "retail-recommendations-449216_cloudbuild"  # Ajustar al nombre real del bucket
  USE_GCS_IMPORT: "true"  # Activar importación via GCS

handlers:
- url: /.*
  script: auto